import logging
import base64
import csv
import traceback

from io import BytesIO
from pathlib import Path

import segno
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as trans
from weasyprint import HTML

logger_portal = logging.getLogger("portal")


def generate_pdf(request, bidder):

    if not bidder: 
        return None

    crm = trans("Generated by ")
    url = f"https://new.emarches.com/bidders/{bidder.id}/"

    try:
        qr_buffer = BytesIO()
        segno.make(url, error='M').save(qr_buffer, kind='svg', scale=8)
        qr_svg_base64 = base64.b64encode(qr_buffer.getvalue()).decode()
        qr_data_uri = f"data:image/svg+xml;base64,{ qr_svg_base64 }"

        logger_portal.debug(f"Started generating PDF file for bidder { bidder.name }")
        context = {
            "request": request,
            "bidder": bidder,
            "crm"           : f'{crm} eMarches.com',
            "qr_code"       : qr_data_uri,
        }

        html_string = render_to_string("insights/bidder-pdf.html", context)
        pdf_file_name = f'eMarches.com-{ bidder.id }-analysis.pdf'
        output_dir = Path(settings.DCE_MEDIA_ROOT) / "bidders" / "pdf"
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"{ pdf_file_name }"

        static_dir  = Path(settings.BASE_DIR) / "static"
        static_uri  = static_dir.resolve().as_uri()
        html_string = html_string.replace('/static/', f'{static_uri}/')        
        HTML(string=html_string).write_pdf(target=output_path)

        return output_path

    except Exception as xc:
        traceback.print_exc()

    return None
    


def generate_csv(bidder):

    if not bidder: 
        return None

    try:

        csv_file_name = f'eMarches.com-{ bidder.id }-analysis.csv'
        output_dir = Path(settings.DCE_MEDIA_ROOT) / "bidders" / "csv"
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"{ csv_file_name }"

        with open(output_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow([
                trans('Tender'),
                trans('Client'), 
                trans('Deadline'), 
                trans('Estimate'), 
                trans('Bond'), 
                trans('Opening date'), 
                trans('Lot Number'), 
                trans('Admin Exam'), 
                trans('Tech Exam'), 
                trans('Bid Amount'), 
                trans('Corrected Amount'),
                trans('Financial Race'),
                trans('Awarded Amount'),
                trans('Awarding justification'),
                ])

            for dep in bidder.deposits.all():
                tender = dep.opening.tender
                admin_result = '?'
                if dep.admin == 'a': admin_result = trans('Accepted') 
                if dep.admin == 'x': admin_result = trans('Rejected') 
                if dep.admin == 'r': admin_result = trans('Reserve') 
                tech_result = trans('Rejected') if dep.reject_t else ""
                fin_result = trans('Awarded') if dep.winner else ""
                writer.writerow([
                    tender.title,
                    tender.client.name,
                    tender.deadline.date(),
                    tender.estimate,
                    tender.bond,
                    dep.opening.date,
                    dep.lot_number,	
                    admin_result,
                    tech_result,
                    dep.amount_b,
                    dep.amount_a,
                    fin_result,
                    dep.amount_w,
                    dep.justif,
                ])
        return output_path

    except Exception as xc:
        traceback.print_exc()

    return None
    



