
import csv

from django.template.loader import render_to_string

from weasyprint import HTML

from django.conf import settings
from pathlib import Path

import segno
from io import BytesIO
import base64

from django.utils.translation import gettext_lazy as trans

empty_items = ['-', '--', '_', '__', '---', '***', '/', 
    '?', '??', '???', ' ', '.', '..', '...', '',
    'Aucune', 'Non'
]

def create_bdc_items_pdf(bdc):

    crm = trans("Generated by ")
    url = "https://new.emarches.com/bdc/"
    
    if bdc : url += f"details/{bdc.id}"

    qr_buffer = BytesIO()
    segno.make(url, error='M').save(qr_buffer, kind='svg', scale=8)
    qr_svg_base64 = base64.b64encode(qr_buffer.getvalue()).decode()
    qr_data_uri = f"data:image/svg+xml;base64,{ qr_svg_base64 }"

    context = {
        "bdc": bdc,
        'empty_items'  : empty_items,
        "crm": crm + ' ' + 'eMarches.com',
        "qr_code": qr_data_uri,
    }

    html_string = render_to_string("bdc/bdc-articles-pdf.html", context)

    pdf_file_name = f'eMarches.com-{ bdc.chrono }-items.pdf'
    output_dir = Path(settings.DCE_MEDIA_ROOT) / "bdc" / "items" / "pdf" / f"{ bdc.id }"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{ pdf_file_name }"

    static_dir  = Path(settings.BASE_DIR) / "static"
    static_uri  = static_dir.resolve().as_uri()

    html_string = html_string.replace('/static/', f'{static_uri}/')

    HTML(string=html_string).write_pdf(target=output_path)
    
    return output_path


def bdc_generate_items_csv(bdc):

    csv_file_name = f'eMarches.com-{ bdc.chrono }-items.csv'
    output_dir = Path(settings.DCE_MEDIA_ROOT) / "bdc" / "items" / "csv" / f"{ bdc.id }"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{ csv_file_name }"
    

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            trans('Number'), trans('Title'), trans('UOM'), 
            trans('Quantity'), trans('VAT') + '%', 
            trans('Specifications'), trans('Warranties')
            ])

        for item in bdc.articles.all():
            writer.writerow([
                item.number,
                item.title,
                item.uom,
                item.quantity,
                item.vat_percent,
                item.specifications,
                item.warranties,
            ])

    return output_path


