# Generated by Django 5.2.4 on 2026-01-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='team',
        ),
        migrations.AddField(
            model_name='bid',
            name='bond_returned',
            field=models.BooleanField(default=False, null=True, verbose_name='Bond returned'),
        ),
    ]
