# Generated by Django 5.2.4 on 2026-01-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_remove_bid_team_bid_bond_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='deatils',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deatils',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Submitted'),
        ),
    ]
