# Generated by Django 5.2.4 on 2026-01-11 23:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_adminreject_concurrent_and_more'),
        ('bidding', '0003_bid_deatils_contract_deatils_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='deatils',
            new_name='details',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bond_returned',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Bond returned'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='file_bond',
            field=models.FileField(blank=True, null=True, upload_to='bidding/bonds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'odt', 'odp', 'odx', 'txt'])], verbose_name='Bond file'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='file_other',
            field=models.FileField(blank=True, null=True, upload_to='bidding/others/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'odt', 'odp', 'odx', 'txt'])], verbose_name='Other file'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='file_receipt',
            field=models.FileField(blank=True, null=True, upload_to='bidding/receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'odt', 'odp', 'odx', 'txt'])], verbose_name='Receipt file'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='file_submitted',
            field=models.FileField(blank=True, null=True, upload_to='bidding/submitted/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'odt', 'odp', 'odx', 'txt'])], verbose_name='Submission file'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bids', to='base.lot'),
        ),
    ]
