# Generated by Django 5.2.4 on 2026-01-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_rename_deatils_contract_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='details',
        ),
    ]
