# Generated by Django 5.2.4 on 2026-01-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_remove_contract_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
    ]
