# Generated by Django 5.2.4 on 2026-01-11 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_contract_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='deatils',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='deatils',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='deatils',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='reception',
            old_name='deatils',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deatils',
            new_name='details',
        ),
    ]
