# Generated by Django 5.2.4 on 2026-01-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_rename_deatils_bid_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Amount Corrected'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Amount Submitted'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bond',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Bond'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='result',
            field=models.CharField(blank=True, choices=[('10X', 'Unknown'), ('20A', 'Awarded'), ('30D', 'Admin Rejected'), ('40T', 'Tech Rejected'), ('50U', 'Unselected')], max_length=16, null=True, verbose_name='Result'),
        ),
    ]
