# Generated by Django 5.2.4 on 2026-01-12 23:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0008_alter_bid_amount_c_alter_bid_amount_s_alter_bid_bond_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, editable=False, null=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='bidding.team')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bidding_team_member',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='members', through='bidding.TeamMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
