# Generated by Django 5.2.4 on 2026-01-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0011_remove_bid_file_other_teammember_unique_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bond',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bond_returned',
        ),
        migrations.AddField(
            model_name='bid',
            name='bond_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Bond Amount'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bond_status',
            field=models.CharField(blank=True, choices=[('20F', 'Filed'), ('30R', 'Returned'), ('40L', 'Lost')], max_length=16, null=True, verbose_name='Bond Status'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount_s',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Amount Submitted'),
            preserve_default=False,
        ),
    ]
