# Generated by Django 5.2.4 on 2026-01-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0014_alter_bid_options_bid_bond_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bond_status',
            field=models.CharField(choices=[('10U', 'Preparing'), ('20F', 'Filed'), ('30R', 'Returned'), ('40L', 'Lost')], default='10U', max_length=16, verbose_name='Bond Status'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('10U', 'Preparing'), ('20R', 'Ready'), ('30S', 'Submitted'), ('40F', 'Finished'), ('50X', 'Cancelled')], default='10U', max_length=16, verbose_name='Bid Status'),
        ),
    ]
