# Generated by Django 5.2.4 on 2026-01-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0015_alter_bid_bond_status_alter_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Corrected Amount'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount_s',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Bid Amount'),
        ),
    ]
