# Generated by Django 5.2.4 on 2026-01-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0017_bid_title_alter_bid_bond_status_alter_bid_result_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['company', 'bid_amount', 'date_submitted']},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='amount_s',
            new_name='bid_amount',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='amount_c',
        ),
        migrations.AlterField(
            model_name='bid',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Bid Title'),
        ),
    ]
