# Generated by Django 5.2.4 on 2026-01-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0018_alter_bid_options_rename_amount_s_bid_bid_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['lot', 'date_submitted', 'company', 'bid_amount']},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='company',
        ),
        migrations.RemoveField(
            model_name='income',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contract',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='New Task', max_length=255, verbose_name='Title'),
        ),
    ]
