# Generated by Django 5.2.4 on 2026-01-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0019_alter_bid_options_remove_expense_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='company',
        ),
        migrations.RemoveField(
            model_name='income',
            name='reception',
        ),
    ]
