# Generated by Django 5.2.4 on 2026-01-30 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_adminreject_concurrent_and_more'),
        ('bidding', '0020_remove_income_company_remove_income_reception'),
        ('nas', '0004_usersetting_bidding_check_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminder',
        ),
        migrations.AddField(
            model_name='contact',
            name='creator',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='nas.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='base.lot'),
        ),
    ]
