# Generated by Django 5.2.4 on 2026-01-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0022_alter_task_options_alter_task_assignee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='contract',
        ),
    ]
