# Generated by Django 5.2.4 on 2026-01-30 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0023_remove_expense_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bill_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bill Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenses', to='bidding.contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_paid',
            field=models.DateField(blank=True, null=True, verbose_name='Paid Date'),
        ),
    ]
