# Generated by Django 5.2.4 on 2026-02-01 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0024_alter_expense_bill_date_alter_expense_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bidding/expenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'odt', 'odp', 'odx', 'txt'])], verbose_name='File'),
        ),
    ]
