# Generated by Django 5.2.4 on 2026-02-02 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0025_alter_expense_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='bidding.bid', verbose_name='Bid'),
        ),
    ]
