# Generated by Django 5.2.4 on 2026-02-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0026_alter_expense_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='manager',
        ),
        migrations.AddField(
            model_name='teammember',
            name='patron',
            field=models.BooleanField(default=False, editable=False, null=True),
        ),
    ]
