# Generated by Django 5.2.4 on 2026-02-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0027_remove_teammember_manager_teammember_patron'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='patron',
            new_name='manager',
        ),
    ]
