# Generated by Django 5.2.4 on 2026-02-03 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0028_rename_patron_teammember_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('message', models.CharField(max_length=1024, verbose_name='Message')),
                ('expiry', models.DateTimeField(blank=True, null=True, verbose_name='Expiry date')),
                ('show_my_email', models.BooleanField(default=True, null=True, verbose_name='Show my email')),
                ('cancelled', models.BooleanField(default=False, editable=False, null=True, verbose_name='Cancelled')),
                ('sent_on', models.DateTimeField(auto_now_add=True, verbose_name='Sent on')),
                ('seen_on', models.DateTimeField(auto_now_add=True, verbose_name='Seen on')),
                ('reply_on', models.DateTimeField(auto_now_add=True, verbose_name='Replied on')),
                ('reply', models.CharField(choices=[('0', 'Denied'), ('1', 'Accepted')], default='0', editable=False, max_length=1, verbose_name='Reply')),
                ('response', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Reply message')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='bidding.team')),
            ],
            options={
                'db_table': 'bidding_invitation',
            },
        ),
    ]
