# Generated by Django 5.2.4 on 2026-02-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0029_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='cancelled',
            field=models.BooleanField(default=False, editable=False, verbose_name='Cancelled'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='reply_on',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Replied on'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='seen_on',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Seen on'),
        ),
    ]
