# Generated by Django 5.2.4 on 2026-02-04 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0030_alter_invitation_cancelled_alter_invitation_reply_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='reply',
            field=models.CharField(blank=True, choices=[('0', 'Denied'), ('1', 'Accepted')], editable=False, max_length=1, null=True, verbose_name='Reply'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='team',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='bidding.team'),
        ),
    ]
