# Generated by Django 5.2.4 on 2026-02-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0031_alter_invitation_reply_alter_invitation_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='email',
        ),
        migrations.AddField(
            model_name='invitation',
            name='username',
            field=models.EmailField(default='bbbbb', max_length=254, verbose_name='Username'),
        ),
    ]
