# Generated by Django 5.2.4 on 2026-02-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0032_alter_invitation_options_remove_invitation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='username',
            field=models.EmailField(max_length=254, verbose_name='Username'),
        ),
    ]
