# Generated by Django 5.2.4 on 2026-02-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0035_alter_teammember_options_alter_teammember_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='username',
            field=models.CharField(verbose_name='Username'),
        ),
    ]
