# Generated by Django 5.2.4 on 2026-02-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0036_alter_invitation_message_alter_invitation_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
