# Generated by Django 5.2.4 on 2026-02-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0037_teammember_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
