# Generated by Django 5.2.4 on 2026-02-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0038_teammember_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
