# Generated by Django 5.2.4 on 2026-02-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0039_alter_teammember_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
