# Generated by Django 5.2.4 on 2026-02-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0041_remove_invitation_seen_on_bid_updater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, default='LA-SQUADRA', max_length=255, verbose_name='Name'),
        ),
    ]
