# Generated by Django 5.2.4 on 2026-02-26 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0042_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='file_bond',
            field=models.FileField(blank=True, null=True, upload_to='bidding/bond/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'odt', 'odp', 'odx', 'txt'])], verbose_name='Bond file'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='file_receipt',
            field=models.FileField(blank=True, null=True, upload_to='bidding/receipt/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xls', 'xlsx', 'odt', 'odp', 'odx', 'txt'])], verbose_name='Receipt file'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('10P', 'Pending'), ('20S', 'Started'), ('40E', 'Finished'), ('50X', 'Cancelled')], default='10P', max_length=16, verbose_name='Status'),
        ),
    ]
