# Generated by Django 5.2.4 on 2026-02-28 18:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0042_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='income',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contact',
        ),
        migrations.AlterField(
            model_name='bid',
            name='file_bond',
            field=models.FileField(blank=True, null=True, upload_to='bidding/bond/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='Bond file'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='file_receipt',
            field=models.FileField(blank=True, null=True, upload_to='bidding/receipt/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='Receipt file'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='file_submitted',
            field=models.FileField(blank=True, null=True, upload_to='bidding/submitted/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='Submission file'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file_guarantee',
            field=models.FileField(null=True, upload_to='bidding/guaranties/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='Guarantee file'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file_terms',
            field=models.FileField(null=True, upload_to='bidding/contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='Terms file'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bidding/expenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='income',
            name='file',
            field=models.FileField(null=True, upload_to='bidding/incomes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='file',
            field=models.FileField(null=True, upload_to='bidding/receptions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('10P', 'Pending'), ('20S', 'Started'), ('40E', 'Finished'), ('50X', 'Cancelled')], default='10P', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='bidding.team'),
        ),
    ]
