# Generated by Django 5.2.4 on 2026-02-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0043_remove_expense_contact_remove_income_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='response',
        ),
    ]
