# Generated by Django 5.2.4 on 2026-02-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0044_remove_invitation_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
