# Generated by Django 5.2.4 on 2026-03-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0043_alter_bid_file_bond_alter_bid_file_receipt_and_more'),
        ('bidding', '0045_delete_contact'),
    ]

    operations = [
    ]
