# Generated by Django 5.2.4 on 2026-03-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0047_alter_bid_file_bond_alter_bid_file_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
