# Generated by Django 5.2.4 on 2026-03-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0048_alter_teammember_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bond_amount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=16, null=True, verbose_name='Bond Amount'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_submitted',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_due',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('10P', 'Pending'), ('20S', 'Started'), ('40E', 'Finished'), ('50X', 'Cancelled')], db_index=True, default='10P', max_length=16, verbose_name='Status'),
        ),
    ]
