# Generated by Django 5.2.4 on 2025-10-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='onborded',
            new_name='onboarded',
        ),
    ]
