# Generated by Django 5.2.4 on 2026-01-10 11:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('serial', models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial Number')),
                ('issuer', models.CharField(blank=True, max_length=128, null=True, verbose_name='Issuer')),
                ('holder', models.CharField(blank=True, max_length=128, null=True, verbose_name='Holder')),
                ('owner', models.CharField(blank=True, max_length=128, null=True, verbose_name='Owner')),
                ('issued', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Validity start')),
                ('expiry', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Expiry date')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='nas.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Asset',
                'db_table': 'base_asset',
                'ordering': ['name'],
            },
        ),
    ]
