# Generated by Django 5.2.4 on 2025-10-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0002_rename_onborded_profile_onboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Phone'),
        ),
    ]
