# Generated by Django 5.2.4 on 2026-01-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0002_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='activity',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnss',
            field=models.CharField(blank=True, default='7777777', max_length=64, null=True, verbose_name='CNSS'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, default='Morocco', max_length=64, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='faximili',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='company',
            name='forme',
            field=models.CharField(blank=True, default='SARL', max_length=255, null=True, verbose_name='Juridic form'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ice',
            field=models.CharField(blank=True, default='77777777777777', max_length=64, null=True, verbose_name='ICE'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Descritpion'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rc',
            field=models.CharField(blank=True, default='7777777', max_length=64, null=True, verbose_name='Num. RC'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Region, State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tp',
            field=models.CharField(blank=True, default='7777777', max_length=64, null=True, verbose_name='Tax Pro'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, default='www.mode-777.com', max_length=128, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='company',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='ZIP Code'),
        ),
    ]
