# Generated by Django 5.2.4 on 2026-01-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0003_alter_company_activity_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='bidding_check_amount',
            field=models.BooleanField(default=True, verbose_name='Check submitted amount when editing'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='bidding_check_deadline',
            field=models.BooleanField(default=True, verbose_name='Check Tender dealine when editing'),
        ),
    ]
