# Generated by Django 5.2.4 on 2025-10-15 09:00

# import private_storage.fields
# import private_storage.storage.files
from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0003_alter_profile_about_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
