# Generated by Django 5.2.4 on 2026-02-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0004_usersetting_bidding_check_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='bidding_check_bond',
            field=models.BooleanField(default=True, verbose_name='Check submitted bond when editing'),
        ),
    ]
