# Generated by Django 5.2.4 on 2025-10-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_agrement_options_alter_category_options_and_more'),
        ('nas', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='agrements',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='base.agrement', verbose_name='Agrements'),
        ),
        migrations.AlterField(
            model_name='company',
            name='qualifs',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='base.qualif', verbose_name='Qualifications'),
        ),
    ]
