# Generated by Django 5.2.4 on 2026-02-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0005_usersetting_bidding_check_bond'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='company',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='folders',
        ),
    ]
