# Generated by Django 5.2.4 on 2026-02-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0006_remove_favorite_company_remove_favorite_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invitable',
            field=models.BooleanField(default=True, editable=False, null=True),
        ),
    ]
