# Generated by Django 5.2.4 on 2025-10-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0006_alter_company_agrements_alter_company_qualifs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['rank', 'name']},
        ),
        migrations.AddField(
            model_name='notification',
            name='rank',
            field=models.SmallIntegerField(default=0, verbose_name='Rank'),
        ),
    ]
