# Generated by Django 5.2.4 on 2026-02-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0007_profile_invitable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='invitable',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='general_show_invitations',
            field=models.BooleanField(default=True, verbose_name='Show invitations from other teams'),
        ),
    ]
