# Generated by Django 5.2.4 on 2025-10-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0007_alter_notification_options_notification_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationsubscription',
            options={'ordering': ['rank', '-when']},
        ),
        migrations.AddField(
            model_name='notificationsubscription',
            name='rank',
            field=models.SmallIntegerField(default=0, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='when',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last subscribed'),
        ),
    ]
