# Generated by Django 5.2.4 on 2025-10-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0008_alter_notificationsubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='companies/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='MODE 777', max_length=255, verbose_name='Name'),
        ),
    ]
