# Generated by Django 5.2.4 on 2026-03-04 14:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0008_remove_profile_invitable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='faximili',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.RemoveField(
            model_name='company',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='company',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='company',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='nas/manageriats/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='File'),
        ),
        migrations.CreateModel(
            name='Expirable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('subject', models.CharField(blank=True, max_length=128, null=True, verbose_name='Subject')),
                ('issuer', models.CharField(blank=True, max_length=128, null=True, verbose_name='Issuer')),
                ('holder', models.CharField(blank=True, max_length=128, null=True, verbose_name='Holder')),
                ('validity_start', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Validity start')),
                ('validity_end', models.DateTimeField(blank=True, null=True, verbose_name='Expiry date')),
                ('file', models.FileField(blank=True, null=True, upload_to='nas/expirables/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='File')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expirables', to='nas.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Expirable',
                'db_table': 'nas_expirable',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manageriat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('identity', models.CharField(blank=True, max_length=128, null=True, verbose_name='Identity')),
                ('validity_start', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Validity start')),
                ('validity_end', models.DateTimeField(blank=True, null=True, verbose_name='Expiry date')),
                ('file', models.FileField(blank=True, null=True, upload_to='nas/manageriats/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='File')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageriats', to='nas.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Manageriat',
                'db_table': 'nas_manageriat',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignatureKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('serial', models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial Number')),
                ('issuer', models.CharField(blank=True, max_length=128, null=True, verbose_name='Issuer')),
                ('holder', models.CharField(blank=True, max_length=128, null=True, verbose_name='Holder')),
                ('owner', models.CharField(blank=True, max_length=128, null=True, verbose_name='Owner')),
                ('validity_start', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Validity start')),
                ('validity_end', models.DateTimeField(blank=True, null=True, verbose_name='Expiry date')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_keys', to='nas.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Signature Key',
                'db_table': 'nas_signature_key',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
