# Generated by Django 5.2.4 on 2026-03-04 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0009_remove_company_address_remove_company_faximili_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirable',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Descritpion'),
        ),
        migrations.AddField(
            model_name='manageriat',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Descritpion'),
        ),
        migrations.AddField(
            model_name='signaturekey',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='nas/manageriats/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='File'),
        ),
        migrations.AddField(
            model_name='signaturekey',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Descritpion'),
        ),
        migrations.AlterField(
            model_name='expirable',
            name='validity_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validity start'),
        ),
        migrations.AlterField(
            model_name='manageriat',
            name='validity_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validity start'),
        ),
        migrations.AlterField(
            model_name='signaturekey',
            name='validity_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validity start'),
        ),
    ]
