# Generated by Django 5.2.4 on 2025-10-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0009_company_mobile_alter_company_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='rank',
            field=models.SmallIntegerField(default=0, verbose_name='Rank'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='rank',
            field=models.SmallIntegerField(default=0, verbose_name='Rank'),
        ),
    ]
