# Generated by Django 5.2.4 on 2025-10-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0010_newsletter_rank_newslettersubscription_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
