# Generated by Django 5.2.4 on 2026-03-05 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0010_expirable_note_manageriat_note_signaturekey_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturekey',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='nas/signature_keys/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='File'),
        ),
    ]
