# Generated by Django 5.2.4 on 2025-10-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0011_alter_newslettersubscription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='when',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last subscribed'),
        ),
    ]
