# Generated by Django 5.2.4 on 2026-03-05 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0011_alter_signaturekey_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cnss',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='date_est',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tp',
        ),
        migrations.AlterField(
            model_name='company',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='nas/companies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'tar.gz', 'tgz', 'tar.bz2', 'tar.xz', 'pdf', 'doc', 'docx', 'odt', 'odp', 'odx', 'txt', 'xml', 'json', 'md', 'rtf', 'html', 'jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif', 'xls', 'xlsx', 'ods', 'ots', 'dif', 'dbf', 'csv', 'mpp', 'ppt', 'pptx'])], verbose_name='File'),
        ),
    ]
