# Generated by Django 5.2.4 on 2025-10-20 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_agrement_options_alter_category_options_and_more'),
        ('nas', '0012_alter_newslettersubscription_when'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['rank', 'name']},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['rank', '-when']},
        ),
        migrations.AddField(
            model_name='notificationsent',
            name='change',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='base.change', verbose_name='Change'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='rank',
            field=models.SmallIntegerField(default=0, editable=False, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='rank',
            field=models.SmallIntegerField(default=0, editable=False, verbose_name='Rank'),
        ),
    ]
