# Generated by Django 5.2.4 on 2026-03-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0012_remove_company_cnss_remove_company_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Address'),
        ),
    ]
