# Generated by Django 5.2.4 on 2026-03-10 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0013_remove_company_city_company_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expirable',
            options={'ordering': ['-validity_end', 'name'], 'verbose_name': 'Expirable'},
        ),
        migrations.AlterModelOptions(
            name='manageriat',
            options={'ordering': ['-validity_end', 'name'], 'verbose_name': 'Manageriat'},
        ),
        migrations.AlterModelOptions(
            name='signaturekey',
            options={'ordering': ['-validity_end', 'name'], 'verbose_name': 'Signature Key'},
        ),
        migrations.RemoveField(
            model_name='signaturekey',
            name='owner',
        ),
        migrations.AlterField(
            model_name='expirable',
            name='name',
            field=models.CharField(default='Name', max_length=256, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manageriat',
            name='name',
            field=models.CharField(default='Name', max_length=256, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signaturekey',
            name='name',
            field=models.CharField(default='Name', max_length=256, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name'),
            preserve_default=False,
        ),
    ]
