# Generated by Django 5.2.4 on 2025-10-25 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_procedure_options_procedure_restricted'),
        ('nas', '0013_alter_newsletter_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, default='www.mode-777.com', max_length=128, verbose_name='Website'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_company_per_user'),
        ),
    ]
