# Generated by Django 5.2.4 on 2026-03-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0014_alter_expirable_options_alter_manageriat_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expirable',
            name='holder',
        ),
        migrations.AddField(
            model_name='expirable',
            name='amount_gross',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='Paid Amount (incl. all taxes)'),
        ),
        migrations.AddField(
            model_name='expirable',
            name='amount_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='Taxes Amount'),
        ),
        migrations.AddField(
            model_name='expirable',
            name='group',
            field=models.CharField(choices=[('20S', 'eSign Key'), ('10M', 'Manageriat'), ('30L', 'Rental'), ('40S', 'Services')], default='20S', max_length=16, verbose_name='Group'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
