# Generated by Django 5.2.4 on 2025-10-31 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0014_alter_company_website_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, editable=False, null=True)),
                ('tenders_ordering_field', models.CharField(choices=[('deadline', 'Deadline: Nearest first'), ('-deadline', 'Deadline: Farthest first'), ('estimate', 'Estimate: Smallest first'), ('-estimate', 'Estimate: Largest first'), ('bond', 'Guarantee: Smallest first'), ('-bond', 'Guarantee: Largest first'), ('published', 'Published: Oldest first'), ('-published', 'Published: Newest first')], default='deadline', max_length=10, verbose_name='Tenders: Ordering field')),
                ('tenders_items_per_page', models.CharField(choices=[(5, '5'), (10, '10'), (20, '20'), (25, '25'), (50, '50'), (100, '100')], default=10, max_length=10, verbose_name='Tenders: Items per page')),
                ('tenders_full_bar_days', models.CharField(choices=[(7, '7'), (10, '10'), (15, '15'), (20, '20'), (30, '30'), (45, '45'), (60, '60'), (90, '90'), (180, '180'), (365, '365')], default=30, max_length=10, verbose_name='Tenders: Full progress bar days')),
                ('tenders_show_expired', models.BooleanField(default=False, verbose_name="Tenders: Show today's expired tenders")),
                ('tenders_show_cancelled', models.BooleanField(default=False, verbose_name='Tenders: Show cancelled tenders')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nas_user_setting',
            },
        ),
    ]
