# Generated by Django 5.2.4 on 2026-03-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0015_remove_reaction_comment_remove_reaction_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaturekey',
            name='company',
        ),
        migrations.AlterModelOptions(
            name='expirable',
            options={'ordering': ['group', '-validity_end', 'name'], 'verbose_name': 'Expirable'},
        ),
        migrations.DeleteModel(
            name='Manageriat',
        ),
        migrations.DeleteModel(
            name='SignatureKey',
        ),
    ]
