# Generated by Django 5.2.4 on 2025-11-03 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_tender_keywords_idx_tender_cliwords_idx_and_more'),
        ('nas', '0016_alter_usersetting_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='tenders_full_bar_days',
        ),
        migrations.AddConstraint(
            model_name='download',
            constraint=models.UniqueConstraint(fields=('tender', 'user'), name='unique_download_per_user'),
        ),
    ]
