# Generated by Django 5.2.4 on 2026-03-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0016_remove_signaturekey_company_alter_expirable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='when',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Date Started'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='when',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='sticky',
            name='when',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='tenderview',
            name='when',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Date'),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
