# Generated by Django 5.2.4 on 2025-11-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0017_remove_usersetting_tenders_full_bar_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='tenders_full_bar_days',
            field=models.CharField(choices=[(7, '7'), (10, '10'), (15, '15'), (20, '20'), (30, '30'), (45, '45'), (60, '60'), (90, '90'), (180, '180'), (365, '365')], default=30, max_length=10, verbose_name='Tenders: Full progress bar days'),
        ),
    ]
