# Generated by Django 5.2.4 on 2026-03-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0017_alter_download_when_alter_favorite_when_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, default='MODE 777', max_length=255, verbose_name='Name'),
        ),
    ]
