# Generated by Django 5.2.4 on 2025-11-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0018_usersetting_tenders_full_bar_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_full_bar_days',
            field=models.CharField(choices=[(7, 'Fbd 007'), (10, 'Fbd 010'), (15, 'Fbd 015'), (20, 'Fbd 020'), (30, 'Fbd 030'), (45, 'Fbd 045'), (60, 'Fbd 060'), (90, 'Fbd 090'), (180, 'Fbd 180'), (365, 'Fbd 365')], default=30, max_length=10, verbose_name='Tenders: Full progress bar days'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_items_per_page',
            field=models.CharField(choices=[(5, 'Ipp 005'), (10, 'Ipp 010'), (20, 'Ipp 020'), (25, 'Ipp 025'), (50, 'Ipp 050'), (100, 'Ipp 100'), (250, 'Ipp 250'), (500, 'Ipp 500')], default=10, max_length=10, verbose_name='Tenders: Items per page'),
        ),
    ]
