# Generated by Django 5.2.4 on 2026-09-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0018_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_ordering_field',
            field=models.CharField(choices=[('deadline', 'Deadline ↗'), ('-deadline', 'Deadline ↘'), ('estimate', 'Estimate ↗'), ('-estimate', 'Estimate ↘'), ('bond', 'Guarantee ↗'), ('-bond', 'Guarantee ↘'), ('published', 'Published ↗'), ('-published', 'Published ↘')], default='-deadline', max_length=16, verbose_name='Default sort'),
        ),
    ]
