# Generated by Django 5.2.4 on 2026-09-08 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0019_alter_usersetting_tenders_ordering_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderview',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='general_wrap_long_text',
            field=models.BooleanField(default=True, verbose_name='Do not wrap long text'),
        ),
    ]
