# Generated by Django 5.2.4 on 2025-11-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0020_alter_usersetting_tenders_full_bar_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ar', 'Arabic'), ('zg', 'Amazigh'), ('es', 'Spanish'), ('de', 'German')], default='en', max_length=10, verbose_name='Preferred interface language'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_full_bar_days',
            field=models.CharField(choices=[('7', '7'), ('10', '10'), ('15', '15'), ('20', '20'), ('30', '30'), ('45', '45'), ('60', '60'), ('90', '90'), ('180', '180'), ('365', '365')], default='30', max_length=10, verbose_name='Tenders: Full progress bar days'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_items_per_page',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('25', '25'), ('50', '50'), ('100', '100')], default='10', max_length=10, verbose_name='Tenders: Items per page'),
        ),
    ]
