# Generated by Django 5.2.4 on 2025-11-05 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_tender_keywords_idx_and_more'),
        ('nas', '0021_usersetting_preferred_language_usersetting_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='tags',
        ),
        migrations.CreateModel(
            name='TenderList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('when', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('results', models.SmallIntegerField(default=0, verbose_name='Results count')),
                ('params', models.TextField(verbose_name='Query parameters')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nas_tender_list',
                'ordering': ['-when'],
            },
        ),
        migrations.CreateModel(
            name='TenderView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('when', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('tender', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='base.tender', verbose_name='Tender')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nas_tender_view',
                'ordering': ['-when'],
            },
        ),
    ]
