# Generated by Django 5.2.4 on 2025-11-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0022_remove_favorite_tags_tenderlist_tenderview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenderList',
        ),
    ]
