# Generated by Django 5.2.4 on 2025-11-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0023_delete_tenderlist'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='download',
            name='unique_download_per_user',
        ),
    ]
