# Generated by Django 5.2.4 on 2025-11-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0024_remove_download_unique_download_per_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['-when'], 'verbose_name': 'Tender Download'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='nas.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='folders',
            field=models.ManyToManyField(null=True, related_name='favorites', to='nas.folder', verbose_name='Folders'),
        ),
    ]
