# Generated by Django 5.2.4 on 2025-11-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0025_alter_company_options_alter_download_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='folders',
            field=models.ManyToManyField(related_name='favorites', to='nas.folder', verbose_name='Folders'),
        ),
    ]
