# Generated by Django 5.2.4 on 2025-12-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0026_alter_favorite_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='general_wrap_long_text',
            field=models.BooleanField(default=False, verbose_name='Do not wrap long text'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_ordering_field',
            field=models.CharField(choices=[('deadline', 'Deadline ↗'), ('-deadline', 'Deadline ↘'), ('estimate', 'Estimate ↗'), ('-estimate', 'Estimate ↘'), ('bond', 'Guarantee ↗'), ('-bond', 'Guarantee ↘'), ('published', 'Published ↗'), ('-published', 'Published ↘')], default='deadline', max_length=10, verbose_name='Tenders: Default sort'),
        ),
    ]
