# Generated by Django 5.2.4 on 2025-12-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0027_usersetting_general_wrap_long_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='p_orders_full_bar_days',
            field=models.CharField(choices=[('5', '5'), ('7', '7'), ('15', '15'), ('20', '20'), ('30', '30'), ('60', '60'), ('90', '90')], default='15', max_length=10, verbose_name='P. Orders: Full progress bar days'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='p_orders_items_per_page',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('25', '25'), ('50', '50'), ('100', '100')], default='10', max_length=10, verbose_name='P. Orders: Items per page'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='p_orders_ordering_field',
            field=models.CharField(choices=[('deadline', 'Deadline ↗'), ('-deadline', 'Deadline ↘'), ('estimate', 'Estimate ↗'), ('-estimate', 'Estimate ↘'), ('bond', 'Guarantee ↗'), ('-bond', 'Guarantee ↘'), ('published', 'Published ↗'), ('-published', 'Published ↘')], default='deadline', max_length=10, verbose_name='P. Orders: Default sort'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='p_orders_show_expired',
            field=models.BooleanField(default=False, verbose_name="P. Orders: Show today's expired items"),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_show_expired',
            field=models.BooleanField(default=False, verbose_name="Tenders: Show today's expired items"),
        ),
    ]
