# Generated by Django 5.2.4 on 2025-12-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0028_usersetting_p_orders_full_bar_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='p_orders_full_bar_days',
            field=models.CharField(choices=[('5', '5'), ('7', '7'), ('15', '15'), ('20', '20'), ('30', '30'), ('60', '60'), ('90', '90')], default='15', max_length=16, verbose_name='P. Orders: Full progress bar days'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='p_orders_items_per_page',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('25', '25'), ('50', '50'), ('100', '100')], default='10', max_length=16, verbose_name='P. Orders: Items per page'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='p_orders_ordering_field',
            field=models.CharField(choices=[('deadline', 'Deadline ↗'), ('-deadline', 'Deadline ↘'), ('published', 'Published ↗'), ('-published', 'Published ↘'), ('deliberated', 'Deliberated ↗'), ('-deliberated', 'Deliberated ↘'), ('estimate', 'Estimate ↗'), ('-estimate', 'Estimate ↘'), ('bond', 'Guarantee ↗'), ('-bond', 'Guarantee ↘')], default='deadline', max_length=16, verbose_name='P. Orders: Default sort'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ar', 'Arabic'), ('zg', 'Amazigh'), ('es', 'Spanish'), ('de', 'German')], default='en', max_length=16, verbose_name='Preferred interface language'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_full_bar_days',
            field=models.CharField(choices=[('7', '7'), ('10', '10'), ('15', '15'), ('20', '20'), ('30', '30'), ('45', '45'), ('60', '60'), ('90', '90'), ('180', '180'), ('365', '365')], default='30', max_length=16, verbose_name='Tenders: Full progress bar days'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_items_per_page',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('25', '25'), ('50', '50'), ('100', '100')], default='10', max_length=16, verbose_name='Tenders: Items per page'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_ordering_field',
            field=models.CharField(choices=[('deadline', 'Deadline ↗'), ('-deadline', 'Deadline ↘'), ('estimate', 'Estimate ↗'), ('-estimate', 'Estimate ↘'), ('bond', 'Guarantee ↗'), ('-bond', 'Guarantee ↘'), ('published', 'Published ↗'), ('-published', 'Published ↘')], default='deadline', max_length=16, verbose_name='Tenders: Default sort'),
        ),
    ]
