# Generated by Django 5.2.4 on 2025-12-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0029_alter_usersetting_p_orders_full_bar_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='general_items_per_page',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('30', '30'), ('50', '50'), ('100', '100')], default='20', max_length=16, verbose_name='List items per page'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='p_orders_items_per_page',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('30', '30'), ('50', '50'), ('100', '100')], default='10', max_length=16, verbose_name='P. Orders: Items per page'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='p_orders_ordering_field',
            field=models.CharField(choices=[('deadline', 'Deadline ↗'), ('-deadline', 'Deadline ↘'), ('published', 'Published ↗'), ('-published', 'Published ↘'), ('deliberated', 'Deliberated ↗'), ('-deliberated', 'Deliberated ↘'), ('winner_amount', 'Winner amount ↗'), ('-winner_amount', 'Winner amount ↘')], default='deadline', max_length=16, verbose_name='P. Orders: Default sort'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='p_orders_show_expired',
            field=models.BooleanField(default=True, verbose_name="P. Orders: Show today's expired items"),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_items_per_page',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('30', '30'), ('50', '50'), ('100', '100')], default='10', max_length=16, verbose_name='Tenders: Items per page'),
        ),
    ]
