# Generated by Django 5.2.4 on 2025-12-02 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0009_alter_article_options'),
        ('nas', '0030_usersetting_general_items_per_page_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticky',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, editable=False, null=True)),
                ('when', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Added')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('purchase_order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='stickies', to='bdc.purchaseorder', verbose_name='Purchase Order')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='stickies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nas_stickies',
                'ordering': ['-when'],
            },
        ),
    ]
