# Generated by Django 5.2.4 on 2025-12-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0031_sticky'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='p_orders_first_articles',
            field=models.CharField(choices=[('2', '2'), ('5', '5'), ('10', '10'), ('15', '15'), ('25', '25'), ('50', '50'), ('100', '100')], default='10', max_length=16, verbose_name='First articles to show'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='p_orders_full_bar_days',
            field=models.CharField(choices=[('5', '5'), ('7', '7'), ('15', '15'), ('20', '20'), ('30', '30'), ('60', '60'), ('90', '90')], default='15', max_length=16, verbose_name='Full progress bar days'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='p_orders_items_per_page',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('30', '30'), ('50', '50'), ('100', '100')], default='10', max_length=16, verbose_name='Items per page'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='p_orders_ordering_field',
            field=models.CharField(choices=[('deadline', 'Deadline ↗'), ('-deadline', 'Deadline ↘'), ('published', 'Published ↗'), ('-published', 'Published ↘'), ('deliberated', 'Deliberated ↗'), ('-deliberated', 'Deliberated ↘'), ('winner_amount', 'Winner amount ↗'), ('-winner_amount', 'Winner amount ↘')], default='deadline', max_length=16, verbose_name='Default sort'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='p_orders_show_expired',
            field=models.BooleanField(default=True, verbose_name="Show today's expired items"),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_full_bar_days',
            field=models.CharField(choices=[('7', '7'), ('10', '10'), ('15', '15'), ('20', '20'), ('30', '30'), ('45', '45'), ('60', '60'), ('90', '90'), ('180', '180'), ('365', '365')], default='30', max_length=16, verbose_name='Full progress bar days'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_items_per_page',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('30', '30'), ('50', '50'), ('100', '100')], default='10', max_length=16, verbose_name='Items per page'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_ordering_field',
            field=models.CharField(choices=[('deadline', 'Deadline ↗'), ('-deadline', 'Deadline ↘'), ('estimate', 'Estimate ↗'), ('-estimate', 'Estimate ↘'), ('bond', 'Guarantee ↗'), ('-bond', 'Guarantee ↘'), ('published', 'Published ↗'), ('-published', 'Published ↘')], default='deadline', max_length=16, verbose_name='Default sort'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_show_cancelled',
            field=models.BooleanField(default=False, verbose_name='Show cancelled tenders'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_show_expired',
            field=models.BooleanField(default=False, verbose_name="Show today's expired items"),
        ),
    ]
