# Generated by Django 5.2.4 on 2025-12-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0032_usersetting_p_orders_first_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='p_orders_first_articles',
            field=models.CharField(choices=[('2', '2'), ('5', '5'), ('10', '10'), ('15', '15'), ('25', '25'), ('50', '50'), ('100', '100')], default='5', max_length=16, verbose_name='First articles to show'),
        ),
    ]
