# Generated by Django 5.2.4 on 2025-12-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas', '0033_alter_usersetting_p_orders_first_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='general_items_per_page',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('25', '25'), ('30', '30'), ('50', '50'), ('100', '100')], default='20', max_length=16, verbose_name='List items per page'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='p_orders_items_per_page',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('25', '25'), ('30', '30'), ('50', '50'), ('100', '100')], default='10', max_length=16, verbose_name='Items per page'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='tenders_items_per_page',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('25', '25'), ('30', '30'), ('50', '50'), ('100', '100')], default='10', max_length=16, verbose_name='Items per page'),
        ),
    ]
