# Generated by Django 5.2.4 on 2025-12-23 15:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agrement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short', models.CharField(blank=True, max_length=128, null=True, verbose_name='Acronym')),
                ('name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'License',
                'db_table': 'base_agrement',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'base_category',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short', models.CharField(blank=True, max_length=128, null=True, verbose_name='Acronym')),
                ('name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name')),
                ('ministery', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sector')),
                ('keywords', models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Public Client',
                'db_table': 'base_client',
                'ordering': ['ministery', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Concurrent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, editable=False, null=True)),
                ('name', models.CharField(default='MODE 777', max_length=255, verbose_name='Name')),
                ('ice', models.CharField(blank=True, default='77777777777777', max_length=64, verbose_name='ICE')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='City')),
                ('country', models.CharField(blank=True, default='Morocco', max_length=64, verbose_name='Country')),
                ('date_est', models.DateField(blank=True, null=True, verbose_name='Date Established')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activity', models.CharField(blank=True, max_length=128, verbose_name='Activity')),
                ('sector', models.CharField(blank=True, max_length=128, verbose_name='Sector')),
            ],
            options={
                'db_table': 'base_concurrent',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started', models.DateTimeField(blank=True, null=True, verbose_name='Started')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Finished')),
                ('import_links', models.BooleanField(blank=True, default=False, null=True)),
                ('links_crawled', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('links_imported', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('links_from_saved', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('tenders_created', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('tenders_updated', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('files_downloaded', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('files_failed', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('saving_errors', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'base_crawler',
                'ordering': ['-finished'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Acronym')),
                ('name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Domain',
                'db_table': 'base_domain',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short', models.CharField(blank=True, max_length=128, null=True, verbose_name='Acronym')),
                ('name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Type',
                'db_table': 'base_kind',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_tech', models.BooleanField(blank=True, default=True, null=True)),
                ('failure', models.TextField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_minutes',
                'ordering': ['-date_end'],
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short', models.CharField(blank=True, max_length=128, null=True, verbose_name='Acronym')),
                ('name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Awarding Mode',
                'db_table': 'base_mode',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short', models.CharField(blank=True, max_length=128, null=True, verbose_name='Acronym')),
                ('restricted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Restricted')),
                ('name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Procedure',
                'db_table': 'base_procedure',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qualif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short', models.CharField(blank=True, max_length=128, null=True, verbose_name='Acronym')),
                ('name', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name')),
                ('domain', models.CharField(blank=True, max_length=128, null=True, verbose_name='Domain')),
                ('classe', models.CharField(blank=True, max_length=16, null=True, verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Qualification',
                'db_table': 'base_qualif',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.SmallIntegerField(blank=True, null=True, verbose_name='Number')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Estimate')),
                ('bond', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Bond')),
                ('reserved', models.BooleanField(blank=True, null=True, verbose_name='Reserved to SMB+')),
                ('variant', models.BooleanField(blank=True, null=True, verbose_name='Variants accepted')),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lots', to='base.category', verbose_name='Category')),
            ],
            options={
                'db_table': 'base_lot',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('when', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lot', models.ForeignKey(blank=True, db_column='lot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='base.lot', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Meeting',
                'db_table': 'base_meeting',
                'ordering': ['-when'],
            },
        ),
        migrations.CreateModel(
            name='FailedLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_lots', to='base.minutes')),
            ],
            options={
                'db_table': 'base_failed_lot',
                'ordering': ['lot_number'],
            },
        ),
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='base.minutes')),
            ],
            options={
                'db_table': 'base_bidder',
                'ordering': ['concurrent'],
            },
        ),
        migrations.CreateModel(
            name='AdminReserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reserves', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reserves', to='base.minutes')),
            ],
            options={
                'db_table': 'base_admin_reserve',
                'ordering': ['concurrent', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='AdminReject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_rejects', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_rejects', to='base.minutes')),
            ],
            options={
                'db_table': 'base_admin_reject',
                'ordering': ['concurrent', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='AdminAccept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_accepts', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_accepts', to='base.minutes')),
            ],
            options={
                'db_table': 'base_admin_accept',
                'ordering': ['concurrent', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='RelAgrementLot',
            fields=[
                ('pk', models.CompositePrimaryKey('agrement', 'lot', blank=True, editable=False, primary_key=True, serialize=False)),
                ('agrement', models.ForeignKey(db_column='agrement', on_delete=django.db.models.deletion.CASCADE, to='base.agrement')),
                ('lot', models.ForeignKey(db_column='lot', on_delete=django.db.models.deletion.CASCADE, to='base.lot')),
            ],
            options={
                'db_table': 'base_rel_agrement_lot',
                'unique_together': {('agrement', 'lot')},
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='agrements',
            field=models.ManyToManyField(related_name='lots', through='base.RelAgrementLot', to='base.agrement'),
        ),
        migrations.CreateModel(
            name='RelDomainTender',
            fields=[
                ('pk', models.CompositePrimaryKey('domain', 'tender', blank=True, editable=False, primary_key=True, serialize=False)),
                ('domain', models.ForeignKey(db_column='domain', on_delete=django.db.models.deletion.CASCADE, to='base.domain')),
            ],
            options={
                'db_table': 'base_rel_domain_tender',
            },
        ),
        migrations.CreateModel(
            name='RelQualifLot',
            fields=[
                ('pk', models.CompositePrimaryKey('qualif', 'lot', blank=True, editable=False, primary_key=True, serialize=False)),
                ('lot', models.ForeignKey(db_column='lot', on_delete=django.db.models.deletion.CASCADE, to='base.lot')),
                ('qualif', models.ForeignKey(db_column='qualif', on_delete=django.db.models.deletion.CASCADE, to='base.qualif')),
            ],
            options={
                'db_table': 'base_rel_qualif_lot',
                'unique_together': {('qualif', 'lot')},
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='qualifs',
            field=models.ManyToManyField(related_name='lots', through='base.RelQualifLot', to='base.qualif'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('when', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lot', models.ForeignKey(blank=True, db_column='lot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='base.lot', verbose_name='Lot')),
            ],
            options={
                'db_table': 'base_sample',
                'ordering': ['-when'],
            },
        ),
        migrations.CreateModel(
            name='SelectedBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('amount_before', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('amount_after', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_bids', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_bids', to='base.minutes')),
            ],
            options={
                'db_table': 'base_selected_bid',
                'ordering': ['lot_number', 'amount_after'],
            },
        ),
        migrations.CreateModel(
            name='TechReject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_rejects', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_rejects', to='base.minutes')),
            ],
            options={
                'db_table': 'base_tech_reject',
                'ordering': ['concurrent', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chrono', models.CharField(blank=True, max_length=16, null=True, verbose_name='Portal Id')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('reference', models.CharField(blank=True, max_length=512, null=True, verbose_name='Reference')),
                ('published', models.DateField(blank=True, null=True, verbose_name='Date published')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Bid deadline')),
                ('lots_count', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Lots count')),
                ('estimate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='Total estimate')),
                ('bond', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='Total bond')),
                ('plans_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='Plans price')),
                ('reserved', models.BooleanField(blank=True, null=True, verbose_name='Reserved to SMB+')),
                ('variant', models.BooleanField(blank=True, null=True, verbose_name='Variants accepted')),
                ('has_agrements', models.BooleanField(blank=True, default=False, null=True, verbose_name='Licenses required')),
                ('has_qualifs', models.BooleanField(blank=True, default=False, null=True, verbose_name='Qualifications required')),
                ('has_samples', models.BooleanField(blank=True, default=False, null=True, verbose_name='Samples required')),
                ('has_meetings', models.BooleanField(blank=True, default=False, null=True, verbose_name='In-site visits scheduled')),
                ('has_visits', models.BooleanField(blank=True, default=False, null=True, verbose_name='Meetings scheduled')),
                ('location', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Works execution location')),
                ('ebid', models.SmallIntegerField(blank=True, default=9, null=True, verbose_name='Electronic bid')),
                ('esign', models.SmallIntegerField(blank=True, default=9, null=True, verbose_name='Electronic signature')),
                ('size_read', models.CharField(blank=True, max_length=128, null=True, verbose_name='Files read size')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Files size (bytes)')),
                ('address_withdrawal', models.TextField(blank=True, null=True, verbose_name='Withdrawal address')),
                ('address_bidding', models.TextField(blank=True, null=True, verbose_name='Bidding address')),
                ('address_opening', models.TextField(blank=True, null=True, verbose_name='Awarding address')),
                ('contact_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Contact name')),
                ('contact_phone', models.CharField(blank=True, max_length=256, null=True, verbose_name='Contact phone')),
                ('contact_email', models.CharField(blank=True, max_length=256, null=True, verbose_name='Contact email')),
                ('contact_fax', models.CharField(blank=True, max_length=256, null=True, verbose_name='Contact fax')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Date updated')),
                ('cancelled', models.BooleanField(blank=True, default=False, null=True, verbose_name='Cancelled')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted')),
                ('link', models.CharField(blank=True, max_length=256, null=True, verbose_name='Official link')),
                ('acronym', models.CharField(blank=True, max_length=8, null=True)),
                ('keywords', models.TextField(blank=True, editable=False, null=True)),
                ('cliwords', models.TextField(blank=True, editable=False, null=True)),
                ('refwords', models.TextField(blank=True, editable=False, null=True)),
                ('locwords', models.TextField(blank=True, editable=False, null=True)),
                ('domwords', models.TextField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenders', to='base.category', verbose_name='Category')),
                ('client', models.ForeignKey(blank=True, db_column='client', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenders', to='base.client', verbose_name='Public client')),
                ('domains', models.ManyToManyField(related_name='tenders', through='base.RelDomainTender', to='base.domain', verbose_name='Domains of activity')),
                ('kind', models.ForeignKey(blank=True, db_column='kind', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenders', to='base.kind')),
                ('mode', models.ForeignKey(blank=True, db_column='mode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenders', to='base.mode', verbose_name='Awarding mode')),
                ('procedure', models.ForeignKey(blank=True, db_column='procedure', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenders', to='base.procedure', verbose_name='Procedure')),
            ],
            options={
                'db_table': 'base_tender',
                'ordering': ['-deadline', 'id'],
            },
        ),
        migrations.AddField(
            model_name='reldomaintender',
            name='tender',
            field=models.ForeignKey(db_column='tender', on_delete=django.db.models.deletion.CASCADE, to='base.tender'),
        ),
        migrations.AddField(
            model_name='minutes',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='base.tender'),
        ),
        migrations.AddField(
            model_name='lot',
            name='tender',
            field=models.ForeignKey(blank=True, db_column='tender', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='base.tender'),
        ),
        migrations.CreateModel(
            name='FileToGet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closed', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='Created', max_length=256, null=True)),
                ('tender', models.ForeignKey(blank=True, db_column='tender', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_to_get', to='base.tender')),
            ],
            options={
                'db_table': 'base_file_to_get',
                'ordering': ['-closed', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reported', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Reported')),
                ('changes', models.TextField(blank=True, null=True, verbose_name='Changes')),
                ('tender', models.ForeignKey(blank=True, db_column='tender', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='base.tender', verbose_name='Tender')),
            ],
            options={
                'verbose_name': 'Change',
                'db_table': 'base_change',
                'ordering': ['-reported', 'tender'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('when', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lot', models.ForeignKey(blank=True, db_column='lot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='base.lot', verbose_name='Lot')),
            ],
            options={
                'db_table': 'base_visit',
                'ordering': ['-when'],
            },
        ),
        migrations.CreateModel(
            name='WinJustif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('justif', models.TextField(blank=True, null=True)),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_justifs', to='base.minutes')),
            ],
            options={
                'db_table': 'base_win_justif',
                'ordering': ['lot_number'],
            },
        ),
        migrations.CreateModel(
            name='WinnerBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_bids', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_bids', to='base.minutes')),
            ],
            options={
                'db_table': 'base_winner_bid',
                'ordering': ['lot_number', 'concurrent'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='reldomaintender',
            unique_together={('domain', 'tender')},
        ),
    ]
