# Generated by Django 5.2.7 on 2025-10-07 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelDomainTender',
            fields=[
                ('pk', models.CompositePrimaryKey('domain', 'tender', blank=True, editable=False, primary_key=True, serialize=False)),
                ('domain', models.ForeignKey(db_column='domain', on_delete=django.db.models.deletion.CASCADE, to='base.domain')),
                ('tender', models.ForeignKey(db_column='tender', on_delete=django.db.models.deletion.CASCADE, to='base.tender')),
            ],
            options={
                'db_table': 'rel_domain_tender',
                'unique_together': {('domain', 'tender')},
            },
        ),
        migrations.AddField(
            model_name='tender',
            name='domains',
            field=models.ManyToManyField(related_name='tenders', through='base.RelDomainTender', to='base.domain'),
        ),
    ]
