# Generated by Django 5.2.4 on 2025-12-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurrent',
            name='short',
            field=models.CharField(default='M7', max_length=255, verbose_name='Acronym'),
        ),
        migrations.AddField(
            model_name='minutes',
            name='won_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='minutes',
            name='won_total',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='concurrent',
            name='ice',
            field=models.CharField(blank=True, default='77777777777777', max_length=64, verbose_name='I.C.E'),
        ),
    ]
