# Generated by Django 5.2.4 on 2025-10-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reldomaintender_tender_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='ebid',
            field=models.SmallIntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='esign',
            field=models.SmallIntegerField(blank=True, default=9, null=True),
        ),
    ]
