# Generated by Django 5.2.4 on 2025-12-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_concurrent_short_minutes_won_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutes',
            name='won_amount',
        ),
        migrations.RemoveField(
            model_name='minutes',
            name='won_total',
        ),
    ]
