# Generated by Django 5.2.4 on 2025-12-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_minutes_won_amount_remove_minutes_won_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminaccept',
            options={'ordering': ['minutes', 'concurrent', 'lot_number']},
        ),
        migrations.AlterModelOptions(
            name='adminreject',
            options={'ordering': ['minutes', 'concurrent', 'lot_number']},
        ),
        migrations.AlterModelOptions(
            name='adminreserve',
            options={'ordering': ['minutes', 'concurrent', 'lot_number']},
        ),
        migrations.AlterModelOptions(
            name='bidder',
            options={'ordering': ['minutes', 'concurrent']},
        ),
        migrations.AlterModelOptions(
            name='failedlot',
            options={'ordering': ['minutes', 'lot_number']},
        ),
        migrations.AlterModelOptions(
            name='minutes',
            options={'ordering': ['-date_end', 'tender']},
        ),
        migrations.AlterModelOptions(
            name='selectedbid',
            options={'ordering': ['minutes', 'lot_number', 'amount_after']},
        ),
        migrations.AlterModelOptions(
            name='techreject',
            options={'ordering': ['minutes', 'concurrent', 'lot_number']},
        ),
        migrations.AlterModelOptions(
            name='winjustif',
            options={'ordering': ['minutes', 'lot_number']},
        ),
        migrations.AlterModelOptions(
            name='winnerbid',
            options={'ordering': ['minutes', 'lot_number', 'concurrent']},
        ),
        migrations.RemoveField(
            model_name='concurrent',
            name='active',
        ),
        migrations.RemoveField(
            model_name='concurrent',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='concurrent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='concurrent',
            name='country',
        ),
        migrations.RemoveField(
            model_name='concurrent',
            name='date_est',
        ),
        migrations.RemoveField(
            model_name='concurrent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='concurrent',
            name='ice',
        ),
        migrations.RemoveField(
            model_name='concurrent',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='concurrent',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='concurrent',
            name='short',
        ),
    ]
