# Generated by Django 5.2.4 on 2025-10-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_tender_ebid_alter_tender_esign'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agrement',
            table='base_agrement',
        ),
        migrations.AlterModelTable(
            name='category',
            table='base_category',
        ),
        migrations.AlterModelTable(
            name='change',
            table='base_change',
        ),
        migrations.AlterModelTable(
            name='client',
            table='base_client',
        ),
        migrations.AlterModelTable(
            name='domain',
            table='base_domain',
        ),
        migrations.AlterModelTable(
            name='filetoget',
            table='base_file_to_get',
        ),
        migrations.AlterModelTable(
            name='kind',
            table='base_kind',
        ),
        migrations.AlterModelTable(
            name='lot',
            table='base_lot',
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='base_meeting',
        ),
        migrations.AlterModelTable(
            name='mode',
            table='base_mode',
        ),
        migrations.AlterModelTable(
            name='procedure',
            table='base_procedure',
        ),
        migrations.AlterModelTable(
            name='qualif',
            table='base_qualif',
        ),
        migrations.AlterModelTable(
            name='relagrementlot',
            table='base_rel_agrement_lot',
        ),
        migrations.AlterModelTable(
            name='reldomaintender',
            table='base_rel_domain_tender',
        ),
        migrations.AlterModelTable(
            name='relqualiflot',
            table='base_rel_qualif_lot',
        ),
        migrations.AlterModelTable(
            name='sample',
            table='base_sample',
        ),
        migrations.AlterModelTable(
            name='tender',
            table='base_tender',
        ),
        migrations.AlterModelTable(
            name='visit',
            table='base_visit',
        ),
    ]
