# Generated by Django 5.2.4 on 2025-10-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_agrement_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
