# Generated by Django 5.2.4 on 2025-12-27 10:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_adminaccept_options_alter_adminreject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_tech', models.BooleanField(blank=True, default=True, null=True)),
                ('failure', models.TextField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='base.tender')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('admin', models.CharField(blank=True, choices=[('a', 'Accepted'), ('r', 'Reserve'), ('x', 'Rejected')], max_length=1, null=True, verbose_name='Admin Result')),
                ('reject_t', models.BooleanField(blank=True, null=True)),
                ('amount_b', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('winner', models.BooleanField(blank=True, null=True)),
                ('justif', models.TextField(blank=True, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='base.concurrent')),
                ('opening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='base.opening')),
            ],
        ),
    ]
