# Generated by Django 5.2.4 on 2025-10-14 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_change_changes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agrement',
            options={'ordering': ['name'], 'verbose_name': ''},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['label'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['-reported', 'tender'], 'verbose_name': 'Change'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['ministery', 'name'], 'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['name'], 'verbose_name': 'Domain'},
        ),
        migrations.AlterModelOptions(
            name='kind',
            options={'ordering': ['name'], 'verbose_name': 'Kind'},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['number'], 'verbose_name': 'Lot'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-when'], 'verbose_name': 'Meeting'},
        ),
        migrations.AlterModelOptions(
            name='mode',
            options={'ordering': ['name'], 'verbose_name': 'Mode'},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['name'], 'verbose_name': 'Procedure'},
        ),
        migrations.AlterModelOptions(
            name='qualif',
            options={'ordering': ['name'], 'verbose_name': 'Qualification'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-when'], 'verbose_name': 'Sample'},
        ),
        migrations.AlterModelOptions(
            name='tender',
            options={'verbose_name': 'Tender'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-when'], 'verbose_name': 'Visit'},
        ),
        migrations.AlterField(
            model_name='agrement',
            name='name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='agrement',
            name='short',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='change',
            name='changes',
            field=models.TextField(blank=True, null=True, verbose_name='Changes'),
        ),
        migrations.AlterField(
            model_name='change',
            name='reported',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='change',
            name='tender',
            field=models.ForeignKey(blank=True, db_column='tender', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='base.tender', verbose_name='Tender'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ministery',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='short',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='short',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='short',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='bond',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Bond'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lots', to='base.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Estimate'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='number',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='reserved',
            field=models.BooleanField(blank=True, null=True, verbose_name='Reserved to SMB+'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='variant',
            field=models.BooleanField(blank=True, null=True, verbose_name='Variants accepted'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='lot',
            field=models.ForeignKey(blank=True, db_column='lot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='base.lot', verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='when',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mode',
            name='short',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='short',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='qualif',
            name='classe',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='qualif',
            name='domain',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='qualif',
            name='name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='qualif',
            name='short',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lot',
            field=models.ForeignKey(blank=True, db_column='lot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='base.lot', verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='when',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='address_bidding',
            field=models.TextField(blank=True, null=True, verbose_name='Bidding address'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='address_opening',
            field=models.TextField(blank=True, null=True, verbose_name='Awarding address'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='address_withdrawal',
            field=models.TextField(blank=True, null=True, verbose_name='Withdrawal address'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='bond',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='Total bond'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='cancelled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cancelled'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenders', to='base.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='chrono',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Portal Id'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenders', to='base.client', verbose_name='Public client'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='contact_email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='contact_fax',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Contact fax'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='contact_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bid deadline'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='domains',
            field=models.ManyToManyField(related_name='tenders', through='base.RelDomainTender', to='base.domain', verbose_name='Domains of activity'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='ebid',
            field=models.SmallIntegerField(blank=True, default=9, null=True, verbose_name='Electronic bid'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='esign',
            field=models.SmallIntegerField(blank=True, default=9, null=True, verbose_name='Electronic signature'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='estimate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='Total estimate'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Official link'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='location',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Works execution location'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='lots_count',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Lots count'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='mode',
            field=models.ForeignKey(blank=True, db_column='mode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenders', to='base.mode', verbose_name='Awarding mode'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='plans_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='Plans price'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='procedure',
            field=models.ForeignKey(blank=True, db_column='procedure', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenders', to='base.procedure', verbose_name='Procedure'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='published',
            field=models.DateField(blank=True, null=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='reference',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='reserved',
            field=models.BooleanField(blank=True, null=True, verbose_name='Reserved to SMB+'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Files size (bytes)'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='size_read',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Files read size'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='variant',
            field=models.BooleanField(blank=True, null=True, verbose_name='Variants accepted'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='lot',
            field=models.ForeignKey(blank=True, db_column='lot', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='base.lot', verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='when',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
