# Generated by Django 5.2.4 on 2025-12-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_opening_deposit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['opening', 'lot_number', 'amount']},
        ),
        migrations.AlterModelOptions(
            name='opening',
            options={'ordering': ['-date_end', 'tender']},
        ),
        migrations.AlterModelTable(
            name='deposit',
            table='base_deposit',
        ),
        migrations.AlterModelTable(
            name='opening',
            table='base_opening',
        ),
    ]
