# Generated by Django 5.2.4 on 2025-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_deposit_options_alter_opening_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opening',
            options={'ordering': ['-date', 'tender']},
        ),
        migrations.RenameField(
            model_name='opening',
            old_name='date_end',
            new_name='date',
        ),
        migrations.AddField(
            model_name='deposit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
