# Generated by Django 5.2.4 on 2025-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_agrement_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='procedure',
            name='restricted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Restricted'),
        ),
    ]
