# Generated by Django 5.2.4 on 2025-10-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_procedure_options_procedure_restricted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-when']},
        ),
        migrations.AddField(
            model_name='tender',
            name='has_agrements',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Licenses required'),
        ),
        migrations.AddField(
            model_name='tender',
            name='has_meetings',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='In-site visits scheduled'),
        ),
        migrations.AddField(
            model_name='tender',
            name='has_qualifs',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Qualifications required'),
        ),
        migrations.AddField(
            model_name='tender',
            name='has_samples',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Samples required'),
        ),
        migrations.AddField(
            model_name='tender',
            name='has_visits',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Meetings scheduled'),
        ),
    ]
