# Generated by Django 5.2.4 on 2025-10-26 12:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_procedure_options_procedure_restricted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started', models.DateTimeField(blank=True, null=True, verbose_name='Started')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Finished')),
                ('import_links', models.BooleanField(blank=True, default=False, null=True)),
                ('links_crawled', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('links_imported', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('links_from_saved', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('tenders_created', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('tenders_updated', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('files_downloaded', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('files_failed', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('saving_errors', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'base_crawler',
                'ordering': ['-finished'],
            },
        ),
        migrations.AlterModelOptions(
            name='agrement',
            options={'ordering': ['name'], 'verbose_name': 'License'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['ministery', 'name'], 'verbose_name': 'Public Client'},
        ),
        migrations.AlterModelOptions(
            name='kind',
            options={'ordering': ['name'], 'verbose_name': 'Type'},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='mode',
            options={'ordering': ['name'], 'verbose_name': 'Awarding Mode'},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['name'], 'verbose_name': 'Procedure'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-when']},
        ),
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-deadline', 'id'], 'verbose_name': 'Tender'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-when']},
        ),
        migrations.AddField(
            model_name='tender',
            name='has_agrements',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Licenses required'),
        ),
        migrations.AddField(
            model_name='tender',
            name='has_meetings',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='In-site visits scheduled'),
        ),
        migrations.AddField(
            model_name='tender',
            name='has_qualifs',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Qualifications required'),
        ),
        migrations.AddField(
            model_name='tender',
            name='has_samples',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Samples required'),
        ),
        migrations.AddField(
            model_name='tender',
            name='has_visits',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Meetings scheduled'),
        ),
    ]
