# Generated by Django 5.2.4 on 2025-12-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_deposit_options_rename_amount_deposit_amount_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminreject',
            name='concurrent',
        ),
        migrations.RemoveField(
            model_name='adminreject',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='adminreserve',
            name='concurrent',
        ),
        migrations.RemoveField(
            model_name='adminreserve',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='bidder',
            name='concurrent',
        ),
        migrations.RemoveField(
            model_name='bidder',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='failedlot',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='minutes',
            name='tender',
        ),
        migrations.RemoveField(
            model_name='winnerbid',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='winjustif',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='selectedbid',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='techreject',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='selectedbid',
            name='concurrent',
        ),
        migrations.RemoveField(
            model_name='techreject',
            name='concurrent',
        ),
        migrations.RemoveField(
            model_name='winnerbid',
            name='concurrent',
        ),
        migrations.DeleteModel(
            name='AdminAccept',
        ),
        migrations.DeleteModel(
            name='AdminReject',
        ),
        migrations.DeleteModel(
            name='AdminReserve',
        ),
        migrations.DeleteModel(
            name='Bidder',
        ),
        migrations.DeleteModel(
            name='FailedLot',
        ),
        migrations.DeleteModel(
            name='WinJustif',
        ),
        migrations.DeleteModel(
            name='Minutes',
        ),
        migrations.DeleteModel(
            name='SelectedBid',
        ),
        migrations.DeleteModel(
            name='TechReject',
        ),
        migrations.DeleteModel(
            name='WinnerBid',
        ),
    ]
