# Generated by Django 5.2.4 on 2026-02-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_adminreject_concurrent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='dep_offset',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='win_offset',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='win_offset',
        ),
    ]
