# Generated by Django 5.2.4 on 2025-10-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_client_keywords_tender_keywords_tender_locwords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='cliwords',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
