# Generated by Django 5.2.4 on 2026-02-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_deposit_dep_offset_remove_deposit_win_offset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='won_total',
        ),
    ]
