# Generated by Django 5.2.4 on 2025-10-31 15:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_tender_cliwords'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tender',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='keywords_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cliwords'], name='cliwords_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=django.contrib.postgres.indexes.GinIndex(fields=['refwords'], name='refwords_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=django.contrib.postgres.indexes.GinIndex(fields=['locwords'], name='locwords_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
