# Generated by Django 5.2.4 on 2025-11-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_tender_keywords_idx_tender_cliwords_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tender',
            name='keywords_idx',
        ),
        migrations.RemoveIndex(
            model_name='tender',
            name='cliwords_idx',
        ),
        migrations.RemoveIndex(
            model_name='tender',
            name='refwords_idx',
        ),
        migrations.RemoveIndex(
            model_name='tender',
            name='locwords_idx',
        ),
    ]
