# Generated by Django 5.2.4 on 2026-03-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_opening_won_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='change',
            name='reported',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Date Reported'),
        ),
        migrations.AlterField(
            model_name='concurrent',
            name='name',
            field=models.CharField(db_index=True, default='MODE 777', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='crawler',
            name='finished',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount_a',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount_b',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount_w',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='filetoget',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='number',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=2048, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='chrono',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Bidding deadline'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='ebid',
            field=models.SmallIntegerField(blank=True, default=9, null=True, verbose_name='Electronic bidding'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='location',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Execution location'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='published',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Files bytes'),
        ),
    ]
