# Generated by Django 5.2.4 on 2025-11-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_tender_keywords_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-deadline', 'id']},
        ),
        migrations.AddField(
            model_name='category',
            name='label_ar',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='label_de',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='label_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='label_es',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='label_fr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='label_zg',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name'),
        ),
    ]
