# Generated by Django 5.2.4 on 2026-09-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_category_label_alter_change_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='has_minutes',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Minutes taken'),
        ),
        migrations.AlterField(
            model_name='filetoget',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
