# Generated by Django 5.2.4 on 2025-11-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_tender_options_category_label_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='label_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='label_de',
        ),
        migrations.RemoveField(
            model_name='category',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='label_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='label_fr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='label_zg',
        ),
    ]
