# Generated by Django 5.2.4 on 2026-09-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_tender_has_minutes_alter_filetoget_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurrent',
            name='activity',
            field=models.TextField(null=True, verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='concurrent',
            name='capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Capital'),
        ),
        migrations.AddField(
            model_name='concurrent',
            name='established',
            field=models.DateField(blank=True, null=True, verbose_name='Date Established'),
        ),
        migrations.AddField(
            model_name='concurrent',
            name='ice',
            field=models.CharField(db_index=True, max_length=16, null=True, verbose_name='Enterprise Id - ICE'),
        ),
        migrations.AddField(
            model_name='concurrent',
            name='rc_city',
            field=models.CharField(max_length=16, null=True, verbose_name='Commerce Registry City'),
        ),
        migrations.AddField(
            model_name='concurrent',
            name='rc_number',
            field=models.CharField(db_index=True, max_length=16, null=True, verbose_name='Commerce Registry Number'),
        ),
        migrations.AddField(
            model_name='concurrent',
            name='status',
            field=models.CharField(max_length=32, null=True, verbose_name='Legal Status'),
        ),
    ]
