# Generated by Django 5.2.4 on 2026-09-30 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_concurrent_activity_concurrent_capital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.CharField(default='IP.ADD.RE.SS', max_length=64)),
                ('name', models.CharField(default='HOST', max_length=64)),
                ('python', models.CharField(max_length=64)),
                ('base_dir', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'base_machine',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Started')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Finished')),
                ('links_handled', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('tenders_created', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('tenders_updated', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('tenders_discarded', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('dce_files_downloaded', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('extra_files_downloaded', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('dce_files_failed', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('extra_files_failed', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('successfull', models.BooleanField(blank=True, default=True, null=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='base.machine')),
            ],
            options={
                'db_table': 'base_harvest',
                'ordering': ['-finished'],
            },
        ),
        migrations.CreateModel(
            name='Parkour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started', models.DateTimeField(auto_now_add=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('deadline_min', models.DateField()),
                ('deadline_max', models.DateField()),
                ('published_min', models.DateField()),
                ('published_max', models.DateField()),
                ('page_length', models.CharField(default='500', max_length=8)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='base.machine')),
            ],
            options={
                'db_table': 'base_parkour',
                'ordering': ['-finished'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('published', models.DateField()),
                ('chrono', models.CharField(blank=True, max_length=16, null=True)),
                ('acronym', models.CharField(blank=True, max_length=8, null=True)),
                ('enviro', models.BooleanField(default=False)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawler_links', to='base.tender')),
                ('parkour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='base.parkour')),
            ],
            options={
                'db_table': 'base_link',
                'ordering': ['-created'],
            },
        ),
    ]
