# Generated by Django 5.2.4 on 2025-11-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_category_label_ar_remove_category_label_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ministery',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Sector'),
        ),
    ]
