# Generated by Django 5.2.4 on 2026-09-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_machine_harvest_parkour_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='has_enviro',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Environment clauses'),
        ),
    ]
