# Generated by Django 5.2.4 on 2025-11-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_client_ministery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='domwords',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
