# Generated by Django 5.2.4 on 2026-10-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_tender_has_enviro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='enviro',
            new_name='has_enviro',
        ),
        migrations.AddField(
            model_name='link',
            name='handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkour',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
