# Generated by Django 5.2.4 on 2025-12-21 23:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_tender_domwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurrent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, editable=False, null=True)),
                ('name', models.CharField(default='MODE 777', max_length=255, verbose_name='Name')),
                ('ice', models.CharField(blank=True, default='77777777777777', max_length=64, verbose_name='ICE')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='City')),
                ('country', models.CharField(blank=True, default='Morocco', max_length=64, verbose_name='Country')),
                ('date_est', models.DateField(blank=True, null=True, verbose_name='Date Established')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activity', models.CharField(blank=True, max_length=128, verbose_name='Activity')),
                ('sector', models.CharField(blank=True, max_length=128, verbose_name='Sector')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'base_concurrent',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('failure', models.CharField(blank=True, max_length=512, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='base.tender')),
            ],
            options={
                'db_table': 'base_minutes',
                'ordering': ['-date_end'],
            },
        ),
        migrations.CreateModel(
            name='FailedLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_lots', to='base.minutes')),
            ],
            options={
                'db_table': 'base_failed_lot',
                'ordering': ['lot_number'],
            },
        ),
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='base.minutes')),
            ],
            options={
                'db_table': 'base_bidder',
                'ordering': ['-concurrent'],
            },
        ),
        migrations.CreateModel(
            name='AdminReserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reserves', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reserves', to='base.minutes')),
            ],
            options={
                'db_table': 'base_admin_reserve',
                'ordering': ['-concurrent'],
            },
        ),
        migrations.CreateModel(
            name='AdminReject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_rejects', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_rejects', to='base.minutes')),
            ],
            options={
                'db_table': 'base_admin_reject',
                'ordering': ['-concurrent'],
            },
        ),
        migrations.CreateModel(
            name='AdminAccept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_accepts', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_accepts', to='base.minutes')),
            ],
            options={
                'db_table': 'base_admin_accept',
                'ordering': ['-concurrent'],
            },
        ),
        migrations.CreateModel(
            name='SelectedBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('amount_before', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('amount_after', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_bids', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_bids', to='base.minutes')),
            ],
            options={
                'db_table': 'base_selected_bid',
                'ordering': ['amount_after'],
            },
        ),
        migrations.CreateModel(
            name='TechReject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_rejects', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_rejects', to='base.minutes')),
            ],
            options={
                'db_table': 'base_tech_reject',
                'ordering': ['-concurrent'],
            },
        ),
        migrations.CreateModel(
            name='WinJustif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('justif', models.CharField(blank=True, max_length=512, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_justifs', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_justifs', to='base.minutes')),
            ],
            options={
                'db_table': 'base_win_justif',
                'ordering': ['-concurrent'],
            },
        ),
        migrations.CreateModel(
            name='WinnerBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.SmallIntegerField(blank=True, null=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_bids', to='base.concurrent')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_bids', to='base.minutes')),
            ],
            options={
                'db_table': 'base_winner_bid',
                'ordering': ['-concurrent'],
            },
        ),
    ]
