# Generated by Django 5.2.4 on 2025-12-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_concurrent_minutes_failedlot_bidder_adminreserve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerbid',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
