# Generated by Django 5.2.4 on 2026-10-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_enviro_link_has_enviro_link_handled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['handled', '-created']},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['hostname']},
        ),
        migrations.RemoveField(
            model_name='machine',
            name='base_dir',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='python',
        ),
        migrations.AddField(
            model_name='machine',
            name='architecture',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AddField(
            model_name='machine',
            name='hostname',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AddField(
            model_name='machine',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=64),
        ),
        migrations.AddField(
            model_name='machine',
            name='os_family',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AddField(
            model_name='machine',
            name='os_release',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AddField(
            model_name='machine',
            name='os_version',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AddField(
            model_name='machine',
            name='processor',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AddField(
            model_name='machine',
            name='python_version',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AlterField(
            model_name='link',
            name='has_enviro',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
