# Generated by Django 5.2.4 on 2026-10-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_link_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkour',
            name='deadline_max',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkour',
            name='deadline_min',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkour',
            name='published_max',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkour',
            name='published_min',
            field=models.DateField(blank=True, null=True),
        ),
    ]
