# Generated by Django 5.2.4 on 2025-12-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_winnerbid_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winjustif',
            options={'ordering': ['lot_number']},
        ),
        migrations.RemoveField(
            model_name='winjustif',
            name='concurrent',
        ),
    ]
