# Generated by Django 5.2.4 on 2025-12-22 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_winjustif_options_remove_winjustif_concurrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurrent',
            name='created',
        ),
        migrations.RemoveField(
            model_name='concurrent',
            name='updated',
        ),
    ]
