# Generated by Django 5.2.4 on 2026-10-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_parkour_deadline_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='chrono',
            field=models.CharField(default='-', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='published',
            field=models.DateField(null=True),
        ),
    ]
