# Generated by Django 5.2.4 on 2026-10-06 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_link_chrono_alter_link_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crawler',
        ),
        migrations.AlterField(
            model_name='parkour',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parkours', to='base.machine'),
        ),
    ]
