# Generated by Django 5.2.4 on 2025-12-23 16:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chrono', models.CharField(blank=True, max_length=256, null=True, verbose_name='Portal Id')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('reference', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Reference')),
                ('published', models.DateTimeField(blank=True, null=True, verbose_name='Date published')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Bid deadline')),
                ('location', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Works execution location')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Date updated')),
                ('unsuccessful', models.BooleanField(blank=True, default=False, null=True, verbose_name='Unsuccessful')),
                ('link', models.CharField(blank=True, max_length=512, null=True, verbose_name='Official link')),
                ('nature', models.TextField(blank=True, null=True, verbose_name='Nature of prestations')),
                ('bids_count', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Bids count')),
                ('winner_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, verbose_name='Winner Amount Inc. taxes')),
                ('winner_entity', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Winner entity')),
                ('deliberated', models.DateTimeField(blank=True, null=True, verbose_name='Results published')),
                ('keywords', models.TextField(blank=True, editable=False, null=True)),
                ('cliwords', models.TextField(blank=True, editable=False, null=True)),
                ('refwords', models.TextField(blank=True, editable=False, null=True)),
                ('locwords', models.TextField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_orders', to='base.category', verbose_name='Category')),
                ('client', models.ForeignKey(blank=True, db_column='client', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_orders', to='base.client', verbose_name='Public client')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'db_table': 'base_purchase_order',
                'ordering': ['-deadline', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('link', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Link')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachements', to='bdc.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Attachement',
                'db_table': 'base_attachement',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Rank')),
                ('number', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Number')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='Specifications')),
                ('warranties', models.TextField(blank=True, null=True, verbose_name='Warranties')),
                ('uom', models.CharField(blank=True, default='U', max_length=1024, null=True, verbose_name='Unit of Measure')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Quantity')),
                ('vat_percent', models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=12, null=True, verbose_name='VAT %')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='bdc.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Article',
                'db_table': 'base_article',
                'ordering': ['rank'],
            },
        ),
    ]
