# Generated by Django 5.2.4 on 2025-11-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=512, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='article',
            name='uom',
            field=models.CharField(blank=True, default='U', max_length=1024, null=True, verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='article',
            name='vat_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=512, null=True, verbose_name='VAT %'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='chrono',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Portal Id'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Official link'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='location',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Works execution location'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='winner_entity',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Winner entity'),
        ),
    ]
