# Generated by Django 5.2.4 on 2025-11-21 19:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0002_alter_article_number_alter_article_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='number',
        ),
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, verbose_name='Name')),
                ('link', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Link')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachements', to='bdc.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Attachement',
                'db_table': 'base_join',
                'ordering': ['name'],
            },
        ),
    ]
