# Generated by Django 5.2.4 on 2025-11-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0003_remove_article_number_attachement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['number'], 'verbose_name': 'Article'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='rank',
        ),
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Number'),
        ),
    ]
