# Generated by Django 5.2.4 on 2025-11-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0004_alter_article_options_remove_article_rank_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachement',
            table='base_attachement',
        ),
    ]
