# Generated by Django 5.2.4 on 2025-11-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0005_alter_attachement_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='article',
            name='vat_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=12, null=True, verbose_name='VAT %'),
        ),
    ]
