# Generated by Django 5.2.4 on 2025-11-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0006_alter_article_quantity_alter_article_vat_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Number'),
        ),
    ]
