# Generated by Django 5.2.4 on 2025-11-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0007_alter_article_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rank',
            field=models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Rank'),
        ),
    ]
