# Generated by Django 5.2.4 on 2025-12-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0008_article_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['rank'], 'verbose_name': 'Article'},
        ),
    ]
