# Generated by Django 5.2.4 on 2025-12-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0009_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date published'),
        ),
    ]
